### ISSUE TITLE
The updating of SVGD seems not right?

### ISSUE THREAD

**Issue by Jarvis-K** [dilinwang820/Graphical-SVGD#1]
In `ops.py/svgd()` line $161$ to $165$, the particles are updated with the pre-calculated svgd gradient. Should not it calculate the svgd gradient during each iteration? Did I misunderstand the implementation?

**Comment by dilinwang820** [comment]
Emm..seems not. The code is written in Theano, both theta and svgd_grad would be updated and recomputed at each iteration. You can verify this by tracking their values during the training. The code execution flow might seem a little bit unintuitive if you're more like a Pytorch-er.

**Comment by Jarvis-K** [comment]
Thanks a lot! I do mis-understanding the theano implementation. 
I will close the issue later
